---
title: ASSOCIATION BETWEEN WORKING HOURS AND TOTAL BLOOD CHOLESTEROL AMONG ADULTS IN THE UNTIED STATES
author:
    name: Christian Hicks
    email: chicks5799@sdsu.edu
    affiliation: San Diego State University School of Public Health
abstract: |
 Background. During 2015-2018 in the United States, mean total blood cholesterol was over 190 mg/dL. This is closer to being considered clinically high at 200 mg/dL than it was to achieving the Healthy People goal for 2020 at 177 mg/dL. Previous studies have described associations between long working hours and undesirable cholesterol health in certain sub-populations. International studies have had consistent results within their respective general populations, but published research on the general U.S. population is scarce. This study sought to describe the effect of working hours on cholesterol health amongst the U.S. population at large.
 Methods. Weighted results from the National Health and Nutrition Examination Survey were analyzed for this study. Of the original 9,254 participants, 1,715 were selected by their age, employment status, and relevant health factors to be included for the analysis. Multiple linear regression was used to measure the effect and significance of working hours on cholesterol after adjustment for confounding variables.
 Results. The prevalence of clinically high cholesterol was 37%, and more than 47% had worked more than 40 hours in the past week. Mean total cholesterol was 190.0 mg/dL (SE = 1.4). After adjustment in the linear regression model, each hour of work had a weak association with a reduction in total cholesterol by 0.28 mg/dL. The largest contributors to higher total cholesterol were age and BMI. Observations who worked less than full-time had 4.6% higher prevalence of clinically high total cholesterol, though this difference was not statistically significant.
 Discussion. This study does not provide enough evidence that longer working hours is associated with declining cholesterol health. Results may be confounded by a healthy worker bias; therefore, further studies should obtain data from persons who are no longer working because health condition could influence employment status.
 Conclusion. Further research is needed to control for the healthy worker effect and confirm that the results of this study are truly representative of the general U.S. population.

date: "`r Sys.Date()`"
journal: N/A
bibliography: references.bib
#linenumbers: true
#numbersections: true
csl: elsevier-vancouver.csl
output: rticles::elsevier_article
link-citations: true
urlcolor: blue
header-includes:
  \usepackage{setspace}\doublespacing
---

Introduction
==========================

### Epidemiology of High Cholesterol

The NIH’s National Heart, Lung, and Blood Institute defines high cholesterol, or hypercholesterolemia, as having total blood cholesterol (TC) levels greater than or equal to 200 mg/dL [@nhlbi2001]. More than one third of the United States (U.S.) adult population has high TC and therefore are at a heightened risk for cardiovascular disease (CVD), stroke, and death [@virani2021]. Established risk factors of high cholesterol include obesity, lack of physical activity, a diet high in saturated and trans fats, type 2 diabetes, smoking, increasing age, male gender, and familial hypercholesterolemia [@cdc2020]. The prevalence of high cholesterol in those who are obese has been recorded to be 2.6 times greater than the prevalence of those with standard body mass index (BMI) [@salazar2017]. Persons with type 2 diabetes have been observed to have 1.6-2.4 times higher prevalence of dyslipidemia compared to persons without diabetes [@jacobs2005].

According to the American Heart Association’s Heart Disease and Stroke Statistics—2021 Update, adults aged 20 years or older in 2015-2018 had a mean TC of 190.6 mg/dL [@virani2021]. Healthy People, an evidence-based initiative that sets national 10-year goals to improve the population health of the U.S., chose to target a mean TC of 177.9 mg/dL by the year 2020 [@healthy2020]. Therefore, the mean TC during 2015-2018 was not within the Healthy People goal for 2020. It was also estimated that 93.9 million, or 38.1%, of U.S. adults had high TC [@virani2021]. The estimated number of adults with very high TC was 28 million, or 11.5%. Although the prevalence of high TC in adults had decreased from 18.3% in 2000 to 10.5% in 2018, the report states that the decline is likely due to greater uptake of medications rather than changes in lifestyle. The estimated economic burden of managing and preventing high cholesterol in the U.S. is between $18.5 million and $77 million every year. The estimated burden of CVD, an outcome from having high cholesterol, is $219 billion [@ferrara2021].

### Working Hours

The U.S. Bureau of Labor Statistics reported full-time employees spent an average of 8.78 hours per workday on work or work-related activities [@bls2019]. This becomes 43.9 hours throughout a 5-day workweek. Globally, 36.1% of workers exceed 48 hours each week [@rivera2020]. These numbers surpass many developed countries’ standards and recommendations. The Australian government mandates employers must not work their employees over 38 hours per week without reason [@reynolds2018]. The European Union states that employers ensure their workers do not exceed an average of 48 hours per week including overtime [@euro2021]. The U.S. Fair Labor and Standards Act [@flsa1938] requires overtime pay after 40 hours in a week for nonexempt employees, and there is no maximum number of hours.

When defining long working hours in research, prior studies have used various cut points such as >40 per week [@rivera2020], >80 hours per week [@lee2016], and >11 hours per day [@lemke2017]. According to the U.S. Patient Protection and Affordable Care Act [@ppaca2010], employees working at least 30 hours per week on average are considered full-time. Working long hours leaves less time for reaching the CDC’s guidelines of recommended exercise, diet, and sleep [@artazcoz2009]. It also can expose individuals to greater amounts of work strain and psychological stress. These experiences have been shown to increase other biomarkers such as blood pressure and heart rate instability [@kivimaki2018].

### Literature review

Japanese engineers in the machinery manufacturing industry were observed to have an age interaction when comparing TC across three levels of weekly working hours [@sasaki1999]. Participants that were aged 30-39 and worked 57-63 hours in a week had 17 mg/dL higher mean TC than participants of the same age group that worked less than 57 hours (p<.05). This age and working hours group also had 19 mg/dL higher mean TC than participants working more than 63 hours each week (p<.05). Within participants aged 40-49 years, those working fewer than 57 hours had 41 mg/dL higher mean TC than those working 57-63 hours (p<.001) and 34 mg/dL higher mean TC than those working more than 63 hours (p<.01). All other age groups had no statistical differences within their various levels of working hours.

Researchers examining data from the Korean NHANES data showed 1.8 times higher odds of coronary heart disease (CHD) for men (95% CI: 1.2 – 2.5) and 1.6 times higher odds for women (95% CI: 1.0 – 2.6) working more than 80 hours per week compared to those working 40 hours per week [@lee2016]. The risk of stroke in these two working groups for men was not statistically significant, but women working more than 80 hours had 2.3 times higher odds of stroke (95% CI: 1.5 – 3.7) than women working 40 hours. Lee et al. also noted that results for men showed 1.8 times higher odds of CHD (95% CI: 1.3 – 2.4) for those working less than 30 hours each week compared to those working 40 hours.

A meta-analysis of 25 cohort studies across Europe, the U.S., and Australia observed a 27% increased risk of stroke (95% CI: 1.03 – 1.56) in working 49-54 hours per week compared to 35-40 hours [@kivimaki2015]. The risk of those working more than 55 hours was 33% greater than the 35-40 hours group (95% CI: 1.11 – 1.61). The results from Kivimaki et al. represented 528,908 men and women from cohort studies between 1975-2013 that were initially free from stroke.

In the U.S., a cross-sectional study of truck drivers used linear regression to estimate the effects of various factors such as age, daily working hours, and sleep quality on TC, LDL-C, and HDL-C measurements [@lemke2017]. Working greater than 11 hours daily was associated with an increase in LDL-C by 14.2 mg/dL (95% CI: 3.2 – 25.3 mg/dL). No statistically significant association was observed on TC or HDL-C.

A 22-year follow-up of 873 participants from the Western Australian Pregnancy Cohort of 1981-1991 performed a cross-sectional analysis comparing differences in cholesterol profiles [@reynolds2018]. Reynolds et al. resulted with no statistically significant difference in mean triglyceride measurements of those who were working more than 38 hours each week (98.3 mg/dL) compared to those working 38 hours or less (95.7 mg/dL). Reynolds et al. observed that mean high-density lipoprotein cholesterol (HDL-C) in the group working greater hours was lower by 4.3 mg/dL (p<.001). These results were adjusted for education level, shift work status, workload, and smoking.

Cross-sectional data on French participants of the CONSTANCES cohort showed similar results after adjusting for age, socioeconomic status, alcohol use, physical activity, depression symptoms, and chronic disease [@virtanen2019] Men who were currently working days longer than 10 hours had standardized means statistically higher in TC (0.03, 95% CI: 0.00 – 0.06), higher in low-density lipoprotein cholesterol (LDL-C) (0.04, 95% CI: 0.01 – 0.07), and lower in HDL-C (-0.04, 95% CI: -0.01 – -0.07), compared to men who had never worked longer than 10 hours in a day. Results for women and all cholesterol measurements were not statistically significant. The standardized mean differences in women currently exposed to those never exposed were 0.00 for TC (95% CI: -0.03 – 0.03), -0.01 for LDL-C (-0.05 – 0.02), and 0.00 for HDL-C (-0.03 – 0.04).

### Gaps in the literature

Very few studies that examined associations between working hours and cholesterol health were generalizable to the whole U.S. population. Some methods utilized population cohorts in other comparable countries, but cultural and sociologic differences cannot be ignored before making assumptions. Studies that have used U.S. residents often regard industry-specific populations or unusually high weekly working hours. These limitations prevent much of the previous findings from reflecting the U.S. population at large.

### Summary

Many U.S. adults are working more than the standardized 40-hour schedule, and thus reducing time for healthy behaviors such as sleep and exercise. More time spent working also increases exposure to job-related stress. Nearly 40% of U.S. adults are affected by high cholesterol, which comes as a result of unhealthy behaviors and stress. Prior research has examined long working hours and its association with blood cholesterol levels, but few are generalizable to most U.S. adults. This analysis is unique in that it studies a random selection of working adults to produce results that can represent the general U.S. adult population. 

### Research question

Are greater self-reported hours worked in the prior week associated with higher serum measurements of total cholesterol among employed men and women aged 18-80 years who participated in NHANES 2017-2018? **H0:** There is not an association between greater working hours in the past week and high total blood cholesterol. **H1:** There is a significant positive association between greater working hours in the past week and high total blood cholesterol.

Methods
=======

### Study design and setting

The National Center for Health Statistics (NCHS) administered the National Health and Nutrition Examination Survey (NHANES) in-person to adults and adolescents in the U.S. during 2017 and 2018. This survey recorded cross-sectional health information and measurements for the purpose of estimating nationwide disease prevalence and aiding in health policy development. The sample design was a complex multi-level process that oversampled and undersampled certain demographics that later became weighted to represent the whole noninstitutionalized civilian population of the United States. Participants were interviewed about their personal demographics, health status, and behaviors, while measurements were recorded by a mobile clinic during a standardized physical examination.

### Study population

During 2017-2018 the National Health and Nutrition Examination Survey (NHANES) recruited 9,254 males and females of all ages, including children with parental approval. Of these participants, 1,715 were selected based on their blood tests and questionnaire results. All selected observations had completed TC measurements, worked at least 30 total hours at all jobs during the week prior to being surveyed, were not currently taking cholesterol medication, and were at least 18 years of age. Any participants who refused to answer or were unable to remember their prior week’s total work hours were not included. Also participants missing data for their BMI and income-to-poverty ratio were removed as this information was needed in the multivariable analysis.

### Data sources and measurement

Outcome: TC was recorded by a combined effort of collecting blood samples by the mobile examination clinic and enzymatic assay methods performed by contracted laboratories. Collection of the samples occurred immediately prior to the questionnaire. After the completion of the laboratory analyses, TC was recorded as continuous values with units of milligrams per deciliter (mg/dL) of blood. No exclusions were made solely based on TC values.

Exposure: Total working hours in the week prior to the survey administration was obtained from a series of questions. First participants were asked “In this part of the survey I will ask you questions about your work experience. Which of the following were you doing last week?” The options to answer this question were as followed: Working at a job or business; with a job or business but not at work; looking for work; not working at a job or business; refused; or don’t know. Only those who responded that they worked at a job or business were considered for this study. A follow-up question was asked to those who reported that they worked: “How many hours did you work last week at all jobs or businesses?” The NHANES administrators recorded those who answered between 1 and 5 hours as just “5.” Six to 78 hours were recorded as discrete values. No respondent reported 79 hours, and those who reported 80 or more were recorded as “80” per the NHANES research methods. The goal of this study was to examine full-time workers, therefore observations were excluded from the analysis if they worked less than 30 hours, refused to report, or did not know how many hours they worked last week.

Covariates: Age was recorded at the time of screening and was coded as discrete values of 0-79, and 80 being a topcode representing individuals 80 years of age and older. BMI was a calculated continuous variable (kg/m2) using weight and height measurements taken by the NHANES examiners. Gender was categorized as either male or female, and there were not any missing values in the dataset. Participants were asked if a doctor has ever told them they have high cholesterol in the following format: “Have you ever been told by a doctor or other health professional that your blood cholesterol level was high?” Responses were recorded as either “Yes,” “No,” “Refused,” or “Don’t Know.” For this study, “Refused” and “Don’t know” were collapsed into missing values. Participants were asked to recall how long they spend sitting down each day with the following question: “How much time do you usually spend sitting on a typical day?” Responses were recorded as either discrete values, “Refused,” or “Don’t Know.” The “Refused” and “Don’t Know” responses were collapsed into missing values. Vigorous physical activity at work was measured as “Yes,” “No,” or “Don’t Know” with the following question: “Does your work involve vigorous-intensity activity that causes large increases in breathing or heart rate like carrying or lifting heavy loads, digging or construction work for at least 10 minutes continuously?” The response “Don’t Know” was recoded as missing for this study. Vigorous recreational activity was also inquired in the following format: “In a typical week do you do any vigorous-intensity sports, fitness, or recreational activities that cause large increases in breathing or heart rate like running or basketball for at least 10 minutes continuously?” Responses were coded similarly to the vigorous work activity variable. Participants self-selected their race or ethnicity from these options: Mexican American; Other Hispanic; Non-Hispanic White; Non-Hispanic Black; Non-Hispanic Asian; and Other Race Including Multi-Racial. Mexican American and Other Hispanic were collapsed into a single category called “Hispanic” for this study. Education level was acquired with the following question: “What is the highest grade or level of school you have completed or the highest degree you have received?” Available responses were: less than 9th grade; 9-11th grade; high school graduate/GED or equivalent; some college or AA degree; college graduate or above; refused; don’t know; or missing. For this study, “less than 9th grade” and “9-11th grade” were collapsed into a new category called “No high school diploma or equivalent.” The “Refused” and “Don’t Know” responses were recategorized into missing values. Lastly, Income-to-Poverty Ratio was a calculated continuous variable using the ratio of self-reported household income levels to the participant’s local poverty line. The value “5” was a topcode for any value greater than or equal to 5. The purpose of this topcode was to retain anonymity of participants with very high incomes.

### Efforts to address bias

Those who worked less than full-time in the prior week, defined as less than 30 hours, were removed from the study to prevent a potential bias that could come from observations who had not worked at all or worked very little. Children and adolescents were removed as they may not have lived long enough to observe direct effects of working hours on TC. The final model controlled for the effects of the selected covariates to estimate the unbiased association between prior week working hours and TC.

### Statistical methods

Descriptive and analytic statistics were calculated with R 4.1.1 “Kick Things” and weights included with the NHANES 2017-2018 dataset were utilized. Unweighted analyses were not performed. Alpha was set to 0.05 for all interpretations. Means and standard errors were reported for normally distributed variables while medians and ranges were reported for non-normal distributions.

Simple linear regression with survey weights was used to determine the effects of the continuous variables on TC for the bivariate analysis. Pearson’s correlations were used to describe the strength of these associations. Bartlett’s test for homogeneity was used to determine the inclusion of a categorical variable in the bivariate analysis. Independent t-tests and ANOVA were performed to calculate differences in means for categorical variables. Multiple linear regression with survey weights was used in the adjusted model to determine the effect of prior week working hours on TC. Forward stepwise selection determined inclusion of covariates for the adjusted model. A 10% minimum change in effect of working hours was used as a cutoff for this selection method.

A post-hoc analysis was performed to measure a potential bias resulting from a healthy worker effect. Pearson’s X2 tests were used to compare high TC (>200 mg/dL) prevalence and very high TC (>240 mg/dL) prevalence between those included and those excluded in the current study population. An independent t-test determined the difference in mean TC between the two groups.

Results
=======

### Key findings

- 37.0% of the weighted population had clinically high total blood cholesterol.
- 47.0% reported working more than 40 hours in the prior week.
- Each hour worked was associated with a decrease of total blood cholesterol by 0.28 mg/dL after adjusting for covariates.

### Study population

The NHANES 2017-2018 dataset consisted of 9,254 observations that was reduced to 1,715 observations due to the exclusion criteria of this study. The final study population was weighted to represent 95,960,477 non-institutionalized adults in the United States. The weighted interquartile range for age was 29 – 51 years old. A BMI of 25 or greater was recorded for 72.9% of the weighted population (SE = 1.6%). The prevalence of either college attendance or completion of an advanced degree was 66.2% (SE = 1.7%). Household income at or below poverty lines was calculated in 9.0% of the weighted population (SE = 0.7%).

### Total blood cholesterol

TC was normally distributed amongst the weighted population and had a mean of 190.0 mg/dL (SE = 1.4). Approximately 37.0% had TC $/geqq$ 200 mg/dL (SE = 1.8%) and 9.9% had TC $\geqq$ 240 mg/dL or higher (SE = 1.1%). When considering the Healthy People 2020 target mean TC, 38.5% of the population were at or under 177.9 mg/dL (SE = 1.7%).

### Working hours

Approximately 33.6% of the weighted population worked exactly 40 hours (SE = 1.7%) and 46.9% worked more than 40 hours (SE = 1.8%). The proportion of those who worked between 30-39 hours was 19.4% (SE = 1.4%). Male mean working hours was 46.7 hours (SE = 0.6) whereas the female mean was 42.8 hours (SE = 0.5).

### Bivariate analysis

Prior week working hours had a weak negative unadjusted correlation with TC (R = -0.08) and accounted for a decrease in TC by 0.31 mg/dL for every hour worked (95% CI = -0.53 – -0.09). The strongest positive unadjusted correlation with TC were age (R = 0.31) and BMI (R = 0.12). An increase of 1 year in age was associated with an increase of 0.93 mg/dL (95% CI = 0.72 – 1.1) in TC. For BMI, an increase of 1 unit was associated with an increase of TC by 0.65 mg/dL (95% CI = 0.32 – 0.97). Taking part in vigorous recreational physical activity was associated with a reduction in mean TC by 11.1 mg/dL (95% CI = 5.8 – 16.3). Non-Hispanic Blacks had the lowest mean TC (182.5 mg/dL, SE = 2.2) while the Other and Multi-racial category had the highest mean TC (200.0 mg/dL, SE = 5.3). Higher levels of education generally decreased mean TC, but these differences were not statistically significant.

### Multivariable analysis

The adjusted model more accurately predicted the variance in TC (Adjusted R2 = 0.12) compared to the unadjusted model of prior week working hours (Adjusted R2 = 0.006), though both were not strong predictors. Each hour worked was associated with an average reduction in TC by 0.28 mg/dl (95% CI = -0.44 – -0.11) after adjusting for age, BMI, vigorous recreational activity, income-to-poverty ratio, race, and ethnicity. Age and BMI had the largest effects on TC in the adjusted model. An increase in 1-year of age was associated with an increase in mean TC by 0.8 mg/dL (0.7 – 1.0), and a 1-unit increase of BMI was associated with an increase in mean TC by 0.5 mg/dL (0.2 – 0.7).

### Post-hoc Analysis

Clinically high TC was prevalent in 37.0% of the study population and 41.6% of the excluded population. Clinically high TC was not independent from the two populations (X2 = 7.8, p=.06). Very high TC was prevalent in 9.9% of the study population and 12.3% of the excluded population. This variable was also not independent from the two populations (X2 = 2.2, p=.14). Mean TC in the study population was 2.9 mg/dL lower than that of the excluded population (95% CI: -6.6 – 0.84).

Discussion
==========

### Principal Findings

More than 1 in 3 represented U.S. working adults in this study had clinically high cholesterol, and nearly half of the study population worked more than 40 hours in the prior week.  The hypothesis that a positive association between working hours and TC was not supported, and rather a negative association was observed. Although significant, the predictability of working hours on TC was weak.

### Comparison to Other Studies

Past research has had varying results such as no associations or significant declining of cholesterol health with higher working hours. Sisaki, Iwasaki, and Hisanaga [@sasaki1999] observed a mean TC of 202 mg/dL and a mean of 60 hours worked in a week for their study population. Although their mean TC is similar to this study, the difference in mean working hours is notable. Their research found that observations aged 30-39 working in the mid-length group (57-63 hours each week) had higher TC than the same age group working over 63 hours. This could possibly be another healthy worker effect resulting with healthier people being capable of working longer hours.

The Reynolds et al [@reynolds2018] cohort study resulted with no difference in TC between those who worked 38 hours or fewer in a week compared to those who worked more than 38 hours in a week. They did note that HDL-C was significantly lower in the group that worked more hours. Their determination of working hours may have been more accurate than the NHANES method because in Reynolds et al they asked participants about their usual workweek length as opposed to the most recent work week. This difference changes the hypothesized mechanism from an immediate effect to a long-term exposure effect.

On the other hand, Virtanen et al. [@virtanen2019] resulted with males currently working more than 10 hours in a day having higher TC than males who had never worked more than 10 hours in a day. This difference was mostly attributed to the men who were currently working more than 10 hours in a day that also had over 15 years of this exposure. Fewer years of exposure reduced the strength of this effect. There was no significance in the difference with their female participants. Virtanen et al. had observed a slightly older population from France, with the mean age being 48 years old compared to the median age of 39 in this NHANES study. Comparability is also affected by the difference in how working hours data was collected. Virtanen et al. used daily working hours rather than weekly hours. Weekly hours cannot be calculated because the number of days worked each week are not reported.

Lee et al. [@lee2016] may have also had a healthy worker effect. Their study resulted with risk of CHD increasing 1.8 times for those working less than 30 hours each week when compared to those working 40 hours each week. This could potentially be caused by healthy participants being physically able to work full-time, while unhealthy participants were underemployed due to their health status.

### Strengths, Limitations, and Bias

Working hours and total cholesterol as continuous measurements preserved analytical power when computing associations. This allowed for the use of a linear regression model that would not be affected by biases in categorization. Weighting observations increased the generalizability to a large portion of the U.S. working adult population. Inclusion of physical activity inside and outside workplace environments increased accuracy of the adjusted association between working hours and total cholesterol. Also, using income-to-poverty ratios rather than raw household income accounts for differences in cost of living due to geographic location.
Limitations from NHANES 2017-2018 were inherited to this study as this was the sole source of data. Much of the data was collected as self-reported information and accuracy was subject to the participants’ responses. Blood specimen collection only occurred once and working hours information was asked of only a single week, which can leave randomness unidentifiable. The cross-sectional design of this study prevents the determination of causal associations.
Since only one measurement of TC and working hours was recorded for each participant, the result of that one recording may not represent the truth. The implication of this is that participants could be misclassified based on that one result and put them into categories that they otherwise would not belong in. Also, by limiting the study population to only those participants who are currently working at the time of the NHANES 2017-2018 data collection, the results of this study may be influenced by the healthy worker effect. Those observations that worked many hours may have only been able to do so because of good health, meaning it is possible that unobserved persons who were negatively affected had to reduce their hours or even stop working entirely.

### Findings Implications

The results of this study and comparisons to past research suggest that TC may not be at risk of worsening due to long working hours within the general U.S. population. When researching health effects of work week standards, it may be more important to examine other biomarkers such as blood pressure or micronutrient deficiency. These implications are generalizable to the working adult-aged population in the U.S. because of the weighting method used in the NHANES dataset.
The post-hoc analysis observed that although the excluded population had 4.6% greater prevalence of clinically high TC compared to the study population, this difference was not statistically significant (p=.06). The results though are close enough to warrant further study. If future results have a similar or greater difference, then it could be confirmed that a healthy worker effect occurs with this study design. This effect can be controlled for by included participants who are no longer working, or working reduced hours, and inquiring about their past work exposures.
The cross-sectional design and nature of the questionnaire leaves the long-term exposure associations unaddressed. Therefore, future study into working hours and TC should adopt a longitudinal design in which multiple blood samples are collected and working hours are averaged over time. Additionally, the healthy worker effect could be controlled for by including persons who are no longer working or underemployed. Other effects of working long hours could be identified by asking participants questions regarding specific experiences at work such as stress or eating habits.

Conclusion
==========

Increased working hours were associated with decreased TC. This result differs from past research that concluded with either no association or a positive association. A potential explanation could be that the healthy worker effect caused a bias in this direction due to healthier observations working longer hours. If future results confirm the existence of this bias, then researchers need to consider under- or unemployed populations whose health status affects their ability to work full-time. 

References {#references .unnumbered}
==========
